package trelay

type PacketType byte

const (
	ConnectRequest PacketType = iota + 1
	Disconnect
	SetUserSlot
	PlayerInfo
	PlayerInventorySlot
	RequestWorldData
	WorldInfo
	GetSectionOrRequestSync
	Status
	SendSection
	SectionTileFrame
	SpawnPlayer
	UpdatePlayer
	PlayerActive
	_
	PlayerHP
	ModifyTile
	Time
	DoorToggle
	SendTileSquare
	UpdateItemDrop
	UpdateItemOwner
	NPCUpdate
	StrikeNPCwithHeldItem
	_
	_
	ProjectileUpdate
	NPCStrike
	DestroyProjectile
	TogglePVP
	GetChestContentsOrActiveChest
	ChestItem
	SetChestNameOrOpenChest
	PlaceOrKillChest
	HealEffect
	PlayerZone
	RequestPassword
	SendPassword
	RemoveItemOwner
	SetActiveNPC
	PlayerItemAnimation
	PlayerMana
	ManaEffect
	KillMe
	PlayerTeam
	RequestSign
	UpdateOrDisplaySign
	SetLiquid
	CompleteConnectionAndSpawn
	UpdatePlayerBuff
	SpecialNPCEffect
	Unlock
	AddNPCBuff
	UpdateNPCBuff
	AddPlayerBuff
	UpdateNPCName
	UpdateGoodOrEvil
	PlayMusicItem
	HitSwitch
	NPCHomeUpdate
	SpawnBossOrInvasion
	PlayerDodge
	PaintTile
	PaintWall
	PlayerOrNPCTeleport
	HealOtherPlayer
	_
	ClientUUID
	GetChestName
	CatchNPC_bugs
	ReleaseNPC
	TravellingMerchantInventory
	TeleportationPotion
	AnglerQuest
	CompleteAnglerquesttoday
	NumberOfAnglerQuestsCompleted
	CreateTemporaryAnimation
	ReportInvasionProgress
	PlaceObject
	SyncPlayerChestIndex
	CreateCombatText
	LoadNetModule
	SetNPCKillCount
	SetPlayerStealth
	ForceItemIntoNearestChest
	UpdateTileEntity
	PlaceTileEntity
	AlterItemDrop
	PlaceItemFrame
	UpdateItemDrop_Instanced
	SyncEmoteBubble
	SyncExtraValue
	SocialHandshake
	_
	KillPortal
	PlayerTeleportThroughPortal
	NotifyPlayerNPCKilled
	NotifyPlayerOfEvent
	UpdateMinionTarget
	NPCTeleportThroughPortal
	UpdateShieldStrengths
	NebulaLevelUpRequest
	UpdateMoonLordCountdown
	SetNPCShopItem
	ToggleGemLock
	PoofofSmoke
	SmartChatMessage
	WiredCannonShot
	MassWireOperation
	MassWireOperationConsume
	ToggleBirthdayParty
	GrowFX
	CrystalInvasionStart
	CrystalInvasionWipeAll
	MinionAttackTargetUpdate
	CrystalInvasionSendWaitTime
	PlayerHurtV2
	PlayerDeathV2
	CombatTextString
	Emoji
	TEDisplayDollItemSync
	RequestTileEntityInteraction
	WeaponsRackTryPlacing
	TEHatRackItemSync
	SyncTilePicking
	SyncRevengeMarker
	RemoveRevengeMarker
	LandGolfBallInCup
	FinishedConnectingToServer
	FishOutNPC
	TamperWithNPC
	PlayLegacySound
	FoodPlatterTryPlacing
	UpdatePlayerLuckFactors
	DeadPlayer
	SyncCavernMonsterType
	RequestNPCBuffRemoval
	ClientSyncedInventory
	SetCountsAsHostForGameplay
	SetMiscEventValues
	RequestLucyPopup
	SyncProjectileTrackers
)
