# https://taskfile.dev

version: 3

tasks:
  default:
    cmds:
      - task -l
    silent: true

  install-deps:
    run: once
    cmds:
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
      - go install gotest.tools/gotestsum@latest

  test:
    desc: "Run tests"
    deps:
      - install-deps
    cmds:
      - gotestsum --format testname

  lint:
    desc: "Run golangci linter"
    deps:
      - install-deps
    cmds:
      - golangci-lint run
